### PR TITLE
Update for Elixir 1.5 compatibility

### PR DESCRIPTION
**Pull request by navinpeiris**
`GenEvent` is deprecated since Elixir 1.5 and therefore moving the formatter to use `GenServer` instead.

Fixes https://github.com/victorolinasc/junit-formatter/issues/25

### CODE REVIEW

**Comment by cs-victor-nascimento** [comment]
Besides the failing tests this seems all right. Will take a look at this more closely later.

**Comment by steffenix** [comment]
Any update on this?

**Comment by cs-victor-nascimento** [comment]
I am still looking at the test failures. Not sure why on master I can't reproduce. It seems to me like when switiching to a `GenServer` it leaves the current test suite in a race condition (it fails trying to find files that don't exist because other tests are trying to set envs).

I will probably have to rewrite the way we are testing this. Along the way I will probably remove elixir's 1.1 support too since coveralls demands a 1.2.

Sorry it is taking a while =/

**Comment by cs-victor-nascimento** [comment]
Well, using [asdf](https://github.com/asdf-vm/asdf) I'm reliably triggering the error caught by [Travis](https://travis-ci.org/victorolinasc/junit-formatter/builds/262094362?utm_source=github_status&utm_medium=notification). 

Perhaps we can use a `GenServer` only for version 1.5. I am still investigating. Just wanted to update here.

**Comment by cs-victor-nascimento** [comment]
So, I've opted to make a release that made it incompatible with Elixir version lower than 1.4. This way we can use only the `GenServer` implementation from now on. If people need to support Elixir before 1.4 than use the 1.3 version of the library. 

Thanks @navinpeiris for your PR. I thanked you in the release notes as well.

**Pull request closed without merging**
