### PR TITLE
Add handling of :skipped atom when using ExUnit >= 1.7.0

### PR DESCRIPTION
**Pull request by mengdaming**
Cf. issue #49 for details.

### CODE REVIEW

**Comment by lukad** [comment]
Any chance we can merge this? :)
It would be nice to have the infos about skipped tests available in our CI pipeline.

**Comment by dbuls** [comment]
@mengdaming I think an additional change needs to be made in order for the `skipped="<nr>"` property to be set on the `<testsuite>` element. In `generate_testsuite_xml()` function on [lines 208-212](https://github.com/victorolinasc/junit-formatter/blob/48004d12dad9abeab275d473c359121b78aece6f/lib/formatter.ex#L208) skipped tests property needs to be added, e.g., 
```elixir
[
  ...
  skipped: stats.skipped,
  ...
],
```

**Comment by dbuls** [comment]
@victorolinasc any chance we could get this PR merged in?

**Comment by victorolinasc** [comment]
I will review this as this is simple enough.

I wonder if the specs say anything about the proper way to tag skipped tests. Do you guys have any links to see this through?

**Comment by victorolinasc** [comment]
I will merge this and clean it up on main. I am upping the elixir version requirement to at least 1.7 (though I think we could go straight to 1.10 or something...)

**Comment by victorolinasc** [comment]
Thanks everyone for the contribution! Test now pass and we have proper skipped counting. Version 3.4.0 is now published.

Have a great day you all!

**Comment by dbuls** [comment]
@victorolinasc thanks for the review and @mengdaming for the PR!

**Pull request merged**
